# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
revd <- function(n = 100L, loc = 0, scale = 1) {
    .Call('_echoice2_revd', PACKAGE = 'echoice2', n, loc, scale)
}

revdx <- function(locs, scales) {
    .Call('_echoice2_revdx', PACKAGE = 'echoice2', locs, scales)
}

#' @export
revd0 <- function(n, scale) {
    .Call('_echoice2_revd0', PACKAGE = 'echoice2', n, scale)
}

#' @export
riwish <- function(v, S) {
    .Call('_echoice2_riwish', PACKAGE = 'echoice2', v, S)
}

lndMvnc <- function(x, mu, L) {
    .Call('_echoice2_lndMvnc', PACKAGE = 'echoice2', x, mu, L)
}

#' @export
rmvn <- function(n, mu, sig) {
    .Call('_echoice2_rmvn', PACKAGE = 'echoice2', n, mu, sig)
}

#' @export
ddl <- function(theta, nalts, X, P, A, ntask, p) {
    .Call('_echoice2_ddl', PACKAGE = 'echoice2', theta, nalts, X, P, A, ntask, p)
}

#' @export
ddLLs <- function(THETAS, XX, PP, AA, nalts, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_ddLLs', PACKAGE = 'echoice2', THETAS, XX, PP, AA, nalts, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
loop_dd_RWMH <- function(XX, PP, AA, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_dd_RWMH', PACKAGE = 'echoice2', XX, PP, AA, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
ddlsr <- function(theta, taui, nalts, X, P, A, Afull, ntask, p) {
    .Call('_echoice2_ddlsr', PACKAGE = 'echoice2', theta, taui, nalts, X, P, A, Afull, ntask, p)
}

#' @export
loop_ddrs_RWMH <- function(XX, PP, AA, AAf, tauconst, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_ddrs_RWMH', PACKAGE = 'echoice2', XX, PP, AA, AAf, tauconst, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
ddsrLLs <- function(THETAS, TAUIS, XX, PP, AA, AAf, nalts, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_ddsrLLs', PACKAGE = 'echoice2', THETAS, TAUIS, XX, PP, AA, AAf, nalts, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
ddlsrpr <- function(theta, taui, tau_pr, nalts, X, P, A, Afull, ntask, p) {
    .Call('_echoice2_ddlsrpr', PACKAGE = 'echoice2', theta, taui, tau_pr, nalts, X, P, A, Afull, ntask, p)
}

#' @export
loop_ddrspr_RWMH <- function(XX, PP, AA, AAf, tauconst, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_ddrspr_RWMH', PACKAGE = 'echoice2', XX, PP, AA, AAf, tauconst, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
dddem <- function(PP, AA, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, cores = 1L) {
    .Call('_echoice2_dddem', PACKAGE = 'echoice2', PP, AA, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, cores)
}

#' @export
ddsrdem <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores = 1L) {
    .Call('_echoice2_ddsrdem', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores)
}

#' @export
ddsrprdem <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores = 1L) {
    .Call('_echoice2_ddsrprdem', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores)
}

#' @export
ddprob <- function(PP, AA, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, cores = 1L) {
    .Call('_echoice2_ddprob', PACKAGE = 'echoice2', PP, AA, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, cores)
}

#' @export
ddsrprob <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores = 1L) {
    .Call('_echoice2_ddsrprob', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores)
}

#' @export
ddsrprprob <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores = 1L) {
    .Call('_echoice2_ddsrprprob', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores)
}

#' @export
vdl2 <- function(theta, nalts, sumpxs, X, P, A, ntask, p) {
    .Call('_echoice2_vdl2', PACKAGE = 'echoice2', theta, nalts, sumpxs, X, P, A, ntask, p)
}

#' @export
vd2LL <- function(Theta, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vd2LL', PACKAGE = 'echoice2', Theta, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vd2LLs <- function(THETAS, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vd2LLs', PACKAGE = 'echoice2', THETAS, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
loop_vd2_RWMH <- function(XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_vd2_RWMH', PACKAGE = 'echoice2', XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
vdln <- function(theta, nalts, sumpxs, X, P, A, ntask, p) {
    .Call('_echoice2_vdln', PACKAGE = 'echoice2', theta, nalts, sumpxs, X, P, A, ntask, p)
}

#' @export
vdnLL <- function(Theta, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdnLL', PACKAGE = 'echoice2', Theta, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vdnLLs <- function(THETAS, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdnLLs', PACKAGE = 'echoice2', THETAS, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
loop_vdn_RWMH <- function(XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_vdn_RWMH', PACKAGE = 'echoice2', XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
vdlsr2 <- function(theta, taui, nalts, sumpxs, X, P, A, Afull, ntask, p) {
    .Call('_echoice2_vdlsr2', PACKAGE = 'echoice2', theta, taui, nalts, sumpxs, X, P, A, Afull, ntask, p)
}

#' @export
vdsr2LL <- function(Theta, tauis, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdsr2LL', PACKAGE = 'echoice2', Theta, tauis, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vdsr2LLs <- function(THETAS, TAUIS, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdsr2LLs', PACKAGE = 'echoice2', THETAS, TAUIS, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
loop_vdrs2_RWMH <- function(XX, PP, AA, AAf, tauconst, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_vdrs2_RWMH', PACKAGE = 'echoice2', XX, PP, AA, AAf, tauconst, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
vdlsrpr <- function(theta, taui, tau_pr, nalts, sumpxs, X, P, A, Afull, ntask, p) {
    .Call('_echoice2_vdlsrpr', PACKAGE = 'echoice2', theta, taui, tau_pr, nalts, sumpxs, X, P, A, Afull, ntask, p)
}

#' @export
loop_vdrspr_RWMH <- function(XX, PP, AA, AAf, tauconst, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_vdrspr_RWMH', PACKAGE = 'echoice2', XX, PP, AA, AAf, tauconst, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
vdsrprLL <- function(Theta, tauis, tau_prs, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdsrprLL', PACKAGE = 'echoice2', Theta, tauis, tau_prs, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vdsrprLLs <- function(THETAS, TAUIS, TAU_PR, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdsrprLLs', PACKAGE = 'echoice2', THETAS, TAUIS, TAU_PR, XX, PP, AA, AAf, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vdl_ss <- function(theta, nalts, sumpxs, X, P, A, ntask, p) {
    .Call('_echoice2_vdl_ss', PACKAGE = 'echoice2', theta, nalts, sumpxs, X, P, A, ntask, p)
}

#' @export
loop_vd_ss_RWMH <- function(XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_vd_ss_RWMH', PACKAGE = 'echoice2', XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
vdl_ssQ <- function(theta, nalts, sumpxs, X, P, A, ntask, p) {
    .Call('_echoice2_vdl_ssQ', PACKAGE = 'echoice2', theta, nalts, sumpxs, X, P, A, ntask, p)
}

#' @export
loop_vd_ssQ_RWMH <- function(XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_vd_ssQ_RWMH', PACKAGE = 'echoice2', XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
vdss_LL <- function(Theta, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdss_LL', PACKAGE = 'echoice2', Theta, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vdss_LLs <- function(THETAS, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores = 1L) {
    .Call('_echoice2_vdss_LLs', PACKAGE = 'echoice2', THETAS, XX, PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, p, N, cores)
}

#' @export
vd_demand <- function(psi, gamma, E, prices) {
    .Call('_echoice2_vd_demand', PACKAGE = 'echoice2', psi, gamma, E, prices)
}

#' @export
des_dem_vdm <- function(PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores = 1L) {
    .Call('_echoice2_des_dem_vdm', PACKAGE = 'echoice2', PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores)
}

#' @export
des_dem_vdmn <- function(PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores = 1L) {
    .Call('_echoice2_des_dem_vdmn', PACKAGE = 'echoice2', PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores)
}

#' @export
der_dem_vdm <- function(PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, epsilon, cores = 1L) {
    .Call('_echoice2_der_dem_vdm', PACKAGE = 'echoice2', PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, epsilon, cores)
}

#' @export
des_dem_vdm_screen <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores = 1L) {
    .Call('_echoice2_des_dem_vdm_screen', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores)
}

#' @export
der_dem_vdm_screen <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, epsilon, cores = 1L) {
    .Call('_echoice2_der_dem_vdm_screen', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, epsilon, cores)
}

#' @export
des_dem_vdm_screenpr <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores = 1L) {
    .Call('_echoice2_des_dem_vdm_screenpr', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores)
}

#' @export
der_dem_vdm_screenpr <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, epsilon, cores = 1L) {
    .Call('_echoice2_der_dem_vdm_screenpr', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, epsilon, cores)
}

#' @export
des_dem_vdm_ss <- function(PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores = 1L) {
    .Call('_echoice2_des_dem_vdm_ss', PACKAGE = 'echoice2', PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores)
}

#' @export
der_dem_vdm_ss <- function(PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, epsilon, cores = 1L) {
    .Call('_echoice2_der_dem_vdm_ss', PACKAGE = 'echoice2', PP, AA, nalts, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, epsilon, cores)
}

#' @export
des_dem_vdm_ssq <- function(PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores = 1L) {
    .Call('_echoice2_des_dem_vdm_ssq', PACKAGE = 'echoice2', PP, AA, nalts, sumpxs, ntasks, xfr, xto, lfr, lto, tlens, thetaDraw, cores)
}

#' @export
der_dem_vdm_ssq <- function(PP, AA, nalts, xlens, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, epsilon, cores = 1L) {
    .Call('_echoice2_der_dem_vdm_ssq', PACKAGE = 'echoice2', PP, AA, nalts, xlens, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, epsilon, cores)
}

#' @export
ec_screen_prob_cpp <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores = 1L) {
    .Call('_echoice2_ec_screen_prob_cpp', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, cores)
}

#' @export
ec_screenpr_prob_cpp <- function(PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores = 1L) {
    .Call('_echoice2_ec_screenpr_prob_cpp', PACKAGE = 'echoice2', PP, AA, AAf, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tauDraw, tau_pr_Draw, cores)
}

#' @export
ddlpr <- function(theta, tau_pr, nalts, X, P, A, ntask, p) {
    .Call('_echoice2_ddlpr', PACKAGE = 'echoice2', theta, tau_pr, nalts, X, P, A, ntask, p)
}

#' @export
loop_ddpr_RWMH <- function(XX, PP, AA, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval = 30L, steptunestart = .5, tunelength = 10000L, tunestart = 500L, progressinterval = 100L, cores = 1L) {
    .Call('_echoice2_loop_ddpr_RWMH', PACKAGE = 'echoice2', XX, PP, AA, nalts, ntasks, xfr, xto, lfr, lto, p, N, R, keep, Bbar, A, nu, V, tuneinterval, steptunestart, tunelength, tunestart, progressinterval, cores)
}

#' @export
ddprdem <- function(PP, AA, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tau_pr_Draw, cores = 1L) {
    .Call('_echoice2_ddprdem', PACKAGE = 'echoice2', PP, AA, nalts, tlens, ntasks, xfr, xto, lfr, lto, thetaDraw, tau_pr_Draw, cores)
}

